version: '3'
services:
  spring-app:
    container_name: spring-app
    ports:
      - "4000:4000"
    environment:
      MYSQL_HOST : mysql
      MYSQL_USER : root
      MYSQL_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    image: jayoung977/backend
    env_file:
      - .env


  react-app:
    container_name: react-app
    ports:
      - "8081:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/statics:/usr/share/nginx/statics
    image: jayoung977/frontend
    env_file:
      - .env



